# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#required-keys
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # weekdays
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: 'github-actions'
    directory: "/"
    schedule:
      interval: "daily"
