name: CI

on:
  push:

jobs:
  # Runs a TypeScript type check
  tsc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --no-fund
      - name: Run tsc
        run: npm run tsc
  # Checks for dependency conflicts that `npm ci` would miss
  npm:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check dependency tree
        run: npm i --package-lock-only --dry-run
  # Builds the extension via Node.js
  webpack:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --no-fund
      - name: Build
        run: npm run webpack
  # Builds the extension via Docker
  docker:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          outputs: type=cacheonly
  # Runs tests
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --no-fund
      - name: Build
        run: npm test
